---
baseline_manage_apparmor_profile_modes: true
baseline_user_initialization_files_regex: '^\.[\w\- ]+$'

baseline_docker_audit_watch_candidates:
  - /usr/bin/docker
  - /usr/bin/dockerd
  - /usr/bin/containerd
  - /usr/bin/containerd-shim-runc-v2
  - /usr/bin/runc
  - /run/containerd
  - /var/lib/docker
  - /etc/docker
  - /etc/default/docker
  - /etc/docker/daemon.json
  - /etc/containerd/config.toml
  - /lib/systemd/system/docker.service
  - /usr/lib/systemd/system/docker.service
  - /lib/systemd/system/docker.socket
  - /usr/lib/systemd/system/docker.socket
  - /var/run/docker.sock
  - /run/containerd/containerd.sock
