---
- name: Restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted
  when:
    - os_auditd_enabled | bool
    - ansible_facts['virtualization_type'] not in ['docker', 'container', 'lxc']

- name: Update grub
  ansible.builtin.command: update-grub
  changed_when: true
